stages:
  - build
  - test
  - deploy_staging_server
  
#before_script:
#  - eval $(ssh-agent -s)
#  - echo "$SSH_PRIVATE_KEY" | tr -d ’\r’ | ssh-add - > /dev/null

build:
  stage: build
  script:
    - echo building

test:
  stage: test
  script:
    - echo testing
    
deploy:
  stage: deploy_staging_server
  script:
    - tar -czvf web.tar.gz frontend
    - scp -o StrictHostKeyChecking=no web.tar.gz g1727114_u@shell2.doc.ic.ac.uk:/vol/project/2017/271/g1727114/
    - ssh g1727114_u@shell2.doc.ic.ac.uk "cd /vol/project/2017/271/g1727114/ && rm -f .htaccess && rm -rf frontend && tar -xzvf web.tar.gz && rm -rf web.tar.gz && mv frontend web"
    #- git remote -v
    #- git pull heroku master
    #- git push heroku master
    - git subtree push --prefix backend_js heroku master
  only:
    - master
    