stages:
  - build
  - test
  - deploy_staging_server
  
#before_script:
#  - eval $(ssh-agent -s)
#  - echo "$SSH_PRIVATE_KEY" | tr -d ’\r’ | ssh-add - > /dev/null

build:
  stage: build
  script:
    - echo building

test:
  stage: test
  script:
    - echo testing
    
deploy:
  stage: deploy_staging_server
  script:
    - rm -rf web.tar.gz
    - tar -czvf web.tar.gz frontend
    #- scp -o StrictHostKeyChecking=no web.tar.gz g1727114_u@shell2.doc.ic.ac.uk:/vol/project/2017/271/g1727114/
    #- ssh g1727114_u@shell2.doc.ic.ac.uk "cd /vol/project/2017/271/g1727114/ && rm -f .htaccess && tar -xzvf web.tar.gz && rm -rf web.tar.gz"
    - heroku -v
    - heroku login
    - rssrwn@gmail.com
    - 057fbe05-8db4-4d43-8720-38de369e15f2
    - heroku git:remote -a edubot-backend
    - git remote -v
    - git subtree push --prefix backend_js heroku master
    #- curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  only:
    - master