stages:
  - build
  - test
  - deploy_staging_server

build:
  stage: build
  script:
    - echo building

test:
  stage: test
  script:
    - echo testing
    
deploy:
  stage: deploy_staging_server
  script:
    - scp -o StrictHostKeyChecking=no elevator_pitch.md g1727114_u@shell2.doc.ic.ac.uk:/vol/project/2017/271/g1727114
    - echo "$g1727114_u_PASSWORD"
  only:
    - master
