stages:
  - build
  - test
  - deploy_staging_server
  
#before_script:
#  - eval $(ssh-agent -s)
#  - echo "$SSH_PRIVATE_KEY" | tr -d ’\r’ | ssh-add - > /dev/null

build:
  stage: build
  script:
    - echo building

test:
  stage: test
  script:
    - echo testing
    
deploy:
  stage: deploy_staging_server
  script:
    - rm -rf frontend.tar.gz
    - tar -czvf frontend.tar.gz frontend
    - scp -o StrictHostKeyChecking=no frontend.tar.gz g1727114_u@shell2.doc.ic.ac.uk:/vol/project/2017/271/g1727114/
    - ssh g1727114_u@shell2.doc.ic.ac.uk "cd /vol/project/2017/271/g1727114/ && tar -xzvf frontend.tar.gz && rm -rf web/* && mv frontend/* web/ && rm -rf frontend.tar.gz"
  only:
    - master
