stages:
  - build
  - test
  - deploy_staging_server
  
before_script:
- eval $(ssh-agent -s)
- echo "$g1727114_u_PASSWORD" | tr -d ’\r’ | ssh-add - > /dev/null

build:
  stage: build
  script:
    - echo building

test:
  stage: test
  script:
    - echo testing
    
deploy:
  stage: deploy_staging_server
  script:
    - scp -o StrictHostKeyChecking=no web/ \
    g1727114_u@146.169.2.83:/vol/project/2017/271/g1727114
  only:
    - master
