stages:
  - build
  - test
  - deploy_staging_server
  
#before_script:
#- eval $(ssh-agent -s)
#- echo "$SSH_PRIVATE_KEY" | tr -d ’\r’ | ssh-add - > /dev/null

build:
  stage: build
  script:
    - echo building

test:
  stage: test
  script:
    - echo testing
    
deploy:
  stage: deploy_staging_server
  script:
    - pwd
    - rm -rf web.zip
    - zip -r web.zip web
    - scp -o StrictHostKeyChecking=no web.zip g1727114_u@shell2.doc.ic.ac.uk:/vol/project/2017/271/g1727114/
    - ssh g1727114_u@shell2.doc.ic.ac.uk
    - cd /vol/project/2017/271/g1727114/
    - rm -rf web
    - unzip web.zip -d .
    - rm -rf web.zip
    - exit
  only:
    - master
